<a href="https://colab.research.google.com/github/shakil1819/CSE404-AI-Sessional/blob/main/202014048_2A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn import metrics

In [2]:
df=pd.read_csv("/content/drive/MyDrive/CSE404- AI-Sessional/Evaluation-sec-B/Amazon_Shoe_dataset_V1 - Sheet1.csv")

In [3]:
df

Shoe_Ratings                                             Review
0               3  "Good shoe for office work. They will scuff ve...
1               1  "I have had the Patricia II wedge in black for...
2               1  "Width not right and size too small if width h...
3               0  "I received these shoes and they weren't the s...
4               2  "They began to split alone the mesh material a...
..            ...                                                ...
195             4  "This is my 3rd purchase. However, the materia...
196             2  "Nice looking shoe and appears to be construct...
197             4  "Great clasp coin wallet. Scripture is nice to...
198             0  "These are super cute shoes, fit my son great ...
199             0  "Was not the color I expected..... Pretty smal...

[200 rows x 2 columns]

In [4]:
df.isnull().sum()

Shoe_Ratings    0
Review          0
dtype: int64

In [7]:
le=preprocessing.LabelEncoder()
y=le.fit_transform(df['Shoe_Ratings'])
y

array([3, 1, 1, 0, 2, 4, 0, 1, 3, 2, 2, 2, 4, 2, 1, 0, 0, 2, 4, 0, 4, 2,
       3, 4, 1, 2, 3, 1, 2, 1, 1, 2, 1, 1, 3, 0, 3, 1, 2, 1, 0, 3, 3, 2,
       3, 4, 4, 1, 4, 4, 2, 1, 0, 1, 4, 4, 3, 1, 4, 4, 3, 1, 1, 3, 4, 4,
       1, 3, 0, 3, 2, 4, 3, 1, 3, 1, 3, 1, 0, 3, 2, 1, 3, 3, 3, 2, 3, 1,
       3, 4, 3, 0, 0, 1, 4, 4, 1, 1, 0, 2, 2, 0, 1, 0, 3, 4, 4, 1, 1, 4,
       3, 2, 0, 3, 3, 4, 1, 1, 2, 2, 0, 1, 4, 0, 0, 1, 2, 4, 1, 2, 0, 0,
       0, 1, 0, 3, 2, 3, 2, 0, 0, 2, 1, 2, 0, 3, 1, 1, 1, 2, 4, 2, 2, 0,
       2, 1, 2, 4, 1, 4, 1, 1, 4, 3, 3, 4, 1, 2, 2, 1, 4, 2, 2, 1, 2, 1,
       4, 3, 3, 2, 0, 1, 4, 2, 2, 2, 0, 1, 3, 4, 1, 4, 2, 0, 4, 4, 2, 4,
       0, 0])

In [9]:
X=df['Review']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [10]:
cv=CountVectorizer()
X_train_encoder=cv.fit_transform(X_train.values)
X_test_encoder=cv.transform(X_test.values)

In [15]:
nb=MultinomialNB()
nb.fit(X_train_encoder,y_train)
y_pred1=nb.predict(X_test_encoder)
print(metrics.precision_score(y_pred1,y_test,average='binary'))
print(metrics.recall_score(y_pred1,y_test))
print(metrics.f1_score(y_pred1,y_test))

ValueError: ignored

In [12]:
vec= TfidfVectorizer()
X_train_vec=vec.fit_transform(X_train.values)
X_test_vec=vec.transform(X_test.values)
vec.get_feature_names_out()

array(['10', '10d', '11', ..., 'zero', 'zip', 'zipper'], dtype=object)

In [16]:
nb=MultinomialNB()
nb.fit(X_train_vec,y_train)
y_pred2=nb.predict(X_test_vec)
print(metrics.precision_score(y_pred2,y_test,average='binary'))
print(metrics.recall_score(y_pred2,y_test))
print(metrics.f1_score(y_pred2,y_test))
print(metrics.accuracy_score(y_pred2,y_test))

ValueError: ignored

In [17]:
def vectorize(tokens):
    ''' This function takes list of words in a sentence as input 
    and returns a vector of size of filtered_vocab.It puts 0 if the 
    word is not present in tokens and count of token if present.'''
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    '''This functions returns a list in which the order remains 
    same and no item repeats.Using the set() function does not 
    preserve the original ordering,so i didnt use that instead'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]
#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","is","a"]
#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]
#Write the sentences in the corpus,in our case, just two 
string1="Welcome to Great Learning , Now start learning"
string2="Learning is a good practice"
#convert them to lower case
string1=string1.lower()
string2=string2.lower()
#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()
print(tokens1)
print(tokens2)
#create a vocabulary list
vocab=unique(tokens1+tokens2)
print(vocab)
#filter the vocabulary list
filtered_vocab=[]
for w in vocab: 
    if w not in stopwords and w not in special_char: 
        filtered_vocab.append(w)
print(filtered_vocab)
#convert sentences into vectords
vector1=vectorize(tokens1)
print(vector1)
vector2=vectorize(tokens2)
print(vector2)

['welcome', 'to', 'great', 'learning', ',', 'now', 'start', 'learning']
['learning', 'is', 'a', 'good', 'practice']
['welcome', 'to', 'great', 'learning', ',', 'now', 'start', 'is', 'a', 'good', 'practice']
['welcome', 'great', 'learning', 'now', 'start', 'good', 'practice']
[1, 1, 2, 1, 1, 0, 0]
[0, 0, 1, 0, 0, 1, 1]


In [18]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
 
sentence_1="Welcome to Great Learning , Now start learning"
sentence_2="Learning is a good practicel"
 
 
 
CountVec = CountVectorizer( # to use bigrams ngram_range=(2,2)
                           stop_words='english')
#transform
Count_data = CountVec.fit_transform([sentence_1,sentence_2])
 
print(Count_data.toarray())
print(CountVec.vocabulary_)

[[0 1 2 0 1 1]
 [1 0 1 1 0 0]]
{'welcome': 5, 'great': 1, 'learning': 2, 'start': 4, 'good': 0, 'practicel': 3}
