<a href="https://colab.research.google.com/github/shakil1819/CSE404-AI-Sessional/blob/main/play_or_not.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn import preprocessing

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn import metrics

In [ ]:
play_data=pd.read_csv("/content/drive/MyDrive/AI Lab/Class2/Play.csv")

In [ ]:
play_data.head()

Weather Temp  Play 
0     Sunny   Hot    No
1     Sunny   Hot    No
2  Overcast   Hot   Yes
3     Rainy  Mild   Yes
4    Rainy   Cool   Yes

In [ ]:
play_data.isnull().sum()

Weather    0
Temp       0
Play       0
dtype: int64

In [ ]:
play_data.columns

Index(['Weather', 'Temp ', 'Play '], dtype='object')

In [ ]:
le=preprocessing.LabelEncoder()

weather_encoder=le.fit_transform(play_data['Weather'])
temp_encoder=le.fit_transform(play_data['Temp '])
play_encoder=le.fit_transform(play_data['Play '])

In [ ]:
#play_data['Weather']

0         Sunny
1         Sunny
2      Overcast
3         Rainy
4        Rainy 
5         Rainy
6      Overcast
7         Sunny
8         Sunny
9         Rainy
10        Sunny
11    Overcast 
12    Overcast 
13        Sunny
Name: Weather, dtype: object

In [ ]:
play_data['Weather'].unique()

array(['Sunny', 'Overcast', 'Rainy', 'Rainy ', 'Overcast '], dtype=object)

In [ ]:
weather_encoder

array([4, 4, 0, 2, 3, 2, 0, 4, 4, 2, 4, 1, 1, 4])

In [ ]:
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
play_encoder

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
y=play_encoder
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
X=np.array(list(zip(weather_encoder,temp_encoder)))
X

array([[4, 1],
       [4, 1],
       [0, 1],
       [2, 2],
       [3, 0],
       [2, 0],
       [0, 0],
       [4, 2],
       [4, 0],
       [2, 2],
       [4, 2],
       [1, 2],
       [1, 1],
       [4, 2]])

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
lg= LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=lg.predict(X_test)

In [ ]:
metrics.accuracy_score(y_pred,y_test)

1.0